### ISSUE TITLE
getVenueWithAlias:completionHandler: ne renvoie ni de venue ni d'erreur

### ISSUE THREAD

**Issue by Branlute** [Mapwize/mapwize-ios-sdk#3]
Bonjour,

Je vient de passer de la 1.5.0 à la 1.7, et depuis tous les appels à : 
`MWZMapView getVenueWithAlias:completionHandler: `
retourne un venue et une erreur null.
J'ai regardé ligne 320, le serveur ne retourne pas d' "**_id**" ni d' "**error**". Le problème doit venir de là.

**Comment by emerciercontexeo** [comment]
Bonjour,

J'ai effectué quelques tests et je n'arrive pour le moment pas à reproduire cette erreur.

Pouvez-vous m'envoyer une copie de la ligne que vous executer quand vous utilisez cette méthode ?

**Comment by Branlute** [comment]
Bonjour,

Je n'arrive plus à reproduire l'ano, ça remarche.
Donc je ferme l'issue. On verra si ça se reproduit.

Bonne journée
