### ISSUE TITLE
Appel des handlers même si il n'existe pas

### ISSUE THREAD

**Issue by Branlute** [Mapwize/mapwize-ios-sdk#4]
Bonjour,

Sur les fonctions disposant de handler, il n'y a pas de vérification de leur existence avant de les appeler. Ce qui provoque un crash.

Par exemple pour un 
`MWZMapView access:completionHandler:`
dont on ne veux rien faire une fois que cela est terminé, on met donc **nil** en tant que completionHandler, et cela provoque un crash.

**Comment by emerciercontexeo** [comment]
Bonjour,

Le fonctionnement a été revu afin de ne plus causer de crash en cas d'handler nil.

La correction sera intégrée dans la prochaine release.

**Comment by Branlute** [comment]
Bonjour,

Ok impeccable.

Bonne journée
